# -*- coding: utf-8 -*-
"""HDFS Sequential.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lXmQMdzV6kk0D1B1CSIPszoAla6i9hHz
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("Event_traces.csv")

# sequence parse
df["sequence"] = df["Features"].apply(lambda x: x.strip("[]").split(","))

# label
df["target"] = df["Label"].apply(lambda x: 1 if x == "Fail" else 0)

X = df["sequence"]
y = df["target"].values

from sklearn.model_selection import train_test_split

X_tr, X_te, y_tr, y_te = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

from tensorflow.keras.preprocessing.text import Tokenizer

X_tr_str = X_tr.apply(lambda x: " ".join(x))
X_te_str = X_te.apply(lambda x: " ".join(x))

tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_tr_str)

X_tr_seq = tokenizer.texts_to_sequences(X_tr_str)
X_te_seq = tokenizer.texts_to_sequences(X_te_str)

from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len = 50

X_tr_pad = pad_sequences(X_tr_seq, maxlen=max_len, padding="post")
X_te_pad = pad_sequences(X_te_seq, maxlen=max_len, padding="post")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

vocab_size = len(tokenizer.word_index) + 1

lstm_model = Sequential([
    Embedding(vocab_size, 64),
    LSTM(64),
    Dropout(0.3),
    Dense(32, activation="relu"),
    Dense(1, activation="sigmoid")
])

lstm_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

class_weight = {0:1, 1:2}

lstm_model.fit(
    X_tr_pad,
    y_tr,
    epochs=5,
    batch_size=1024,
    validation_split=0.1,
    class_weight=class_weight
)

import numpy as np

# probability output
lstm_prob_tr = lstm_model.predict(X_tr_pad)
lstm_prob_te = lstm_model.predict(X_te_pad)

print("Sample LSTM prob:", lstm_prob_tr[:5])

# reshape
lstm_prob_tr = lstm_prob_tr.reshape(-1,1)
lstm_prob_te = lstm_prob_te.reshape(-1,1)

# combine with small sequence info
X_tr_final = np.hstack([lstm_prob_tr, X_tr_pad[:, :10]])
X_te_final = np.hstack([lstm_prob_te, X_te_pad[:, :10]])

print("Final shape:", X_tr_final.shape)

from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(max_iter=1000)

clf.fit(X_tr_final, y_tr)

from sklearn.ensemble import IsolationForest

iso = IsolationForest(n_estimators=100, contamination=0.03, random_state=42)

iso.fit(X_tr_final)

# IF score
if_tr = -iso.decision_function(X_tr_final)
if_te = -iso.decision_function(X_te_final)

import numpy as np

X_tr_final2 = np.hstack([X_tr_final, if_tr.reshape(-1,1)])
X_te_final2 = np.hstack([X_te_final, if_te.reshape(-1,1)])

clf2 = LogisticRegression(max_iter=1000)
clf2.fit(X_tr_final2, y_tr)

y_prob = clf2.predict_proba(X_te_final2)[:,1]
y_pred = (y_prob > 0.4).astype(int)

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import IsolationForest
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np

skf = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)

acc_list, f1_list = [], []

tp_total, fp_total, fn_total, tn_total = 0, 0, 0, 0

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):

    print(f"\n===== FOLD {fold+1} =====")

    X_train_fold = X.iloc[train_idx]
    y_train_fold = y[train_idx]

    X_val_fold = X.iloc[val_idx]
    y_val_fold = y[val_idx]

    # 🔹 Tokenization
    X_tr_str = X_train_fold.apply(lambda x: " ".join(x))
    X_val_str = X_val_fold.apply(lambda x: " ".join(x))

    tokenizer = Tokenizer()
    tokenizer.fit_on_texts(X_tr_str)

    X_tr_seq = tokenizer.texts_to_sequences(X_tr_str)
    X_val_seq = tokenizer.texts_to_sequences(X_val_str)

    # 🔹 Padding
    max_len = 50
    X_tr_pad = pad_sequences(X_tr_seq, maxlen=max_len, padding="post")
    X_val_pad = pad_sequences(X_val_seq, maxlen=max_len, padding="post")

    # 🔹 LSTM Model
    vocab_size = len(tokenizer.word_index) + 1

    lstm_model = Sequential([
        Embedding(vocab_size, 64),
        LSTM(64),
        Dropout(0.3),
        Dense(32, activation="relu"),
        Dense(1, activation="sigmoid")
    ])

    lstm_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

    class_weight = {0:1, 1:2}

    lstm_model.fit(
        X_tr_pad,
        y_train_fold,
        epochs=3,
        batch_size=1024,
        verbose=0,
        class_weight=class_weight
    )

    # 🔹 LSTM prob
    lstm_tr = lstm_model.predict(X_tr_pad)
    lstm_val = lstm_model.predict(X_val_pad)

    lstm_tr = lstm_tr.reshape(-1,1)
    lstm_val = lstm_val.reshape(-1,1)

    # 🔹 combine features
    X_tr_final = np.hstack([lstm_tr, X_tr_pad[:, :10]])
    X_val_final = np.hstack([lstm_val, X_val_pad[:, :10]])

    #  Isolation Forest
    iso = IsolationForest(n_estimators=100, contamination=0.03, random_state=42)
    iso.fit(X_tr_final)

    if_tr = -iso.decision_function(X_tr_final)
    if_val = -iso.decision_function(X_val_final)

    X_tr_final2 = np.hstack([X_tr_final, if_tr.reshape(-1,1)])
    X_val_final2 = np.hstack([X_val_final, if_val.reshape(-1,1)])

    # 🔹 Final LR
    clf = LogisticRegression(max_iter=1000)
    clf.fit(X_tr_final2, y_train_fold)

    #  Predict
    y_prob = clf.predict_proba(X_val_final2)[:,1]

    #  threshold tuning
    best_f1 = 0
    best_t = 0.5

    for t in np.arange(0.3, 0.6, 0.05):
        y_pred_temp = (y_prob > t).astype(int)
        f1_temp = f1_score(y_val_fold, y_pred_temp)

        if f1_temp > best_f1:
            best_f1 = f1_temp
            best_t = t

    y_pred = (y_prob > best_t).astype(int)

    # metrics
    acc = accuracy_score(y_val_fold, y_pred)
    f1 = f1_score(y_val_fold, y_pred)

    acc_list.append(acc)
    f1_list.append(f1)

    tn, fp, fn, tp = confusion_matrix(y_val_fold, y_pred).ravel()

    tn_total += tn
    fp_total += fp
    fn_total += fn
    tp_total += tp

    print("Best threshold:", best_t)
    print("Accuracy:", acc)
    print("F1:", f1)
    print("TP:", tp, "FP:", fp, "FN:", fn, "TN:", tn)

#  FINAL RESULT
print("\n===== FINAL RESULT =====")
print("Avg Accuracy:", np.mean(acc_list))
print("Avg F1:", np.mean(f1_list))

print("\nTOTAL CONFUSION MATRIX:")
print("TP:", tp_total)
print("FP:", fp_total)
print("FN:", fn_total)
print("TN:", tn_total)