# -*- coding: utf-8 -*-
"""HDFS RALLEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R3XqEYpZV2cp_qPr4qNY6r4lx80fWVWo
"""



from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("Event_traces.csv")

df["sequence"] = df["Features"].apply(lambda x: x.strip("[]").split(","))
df["target"] = df["Label"].apply(lambda x: 1 if x == "Fail" else 0)

X = df["sequence"]
y = df["target"].values

from sklearn.model_selection import train_test_split

X_tr, X_te, y_tr, y_te = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

X_tr_str = X_tr.apply(lambda x: " ".join(x))
X_te_str = X_te.apply(lambda x: " ".join(x))

tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_tr_str)

X_tr_seq = tokenizer.texts_to_sequences(X_tr_str)
X_te_seq = tokenizer.texts_to_sequences(X_te_str)

max_len = 50
X_tr_pad = pad_sequences(X_tr_seq, maxlen=max_len, padding="post")
X_te_pad = pad_sequences(X_te_seq, maxlen=max_len, padding="post")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

vocab_size = len(tokenizer.word_index) + 1

lstm_model = Sequential([
    Embedding(vocab_size, 64),
    LSTM(64),
    Dropout(0.3),
    Dense(32, activation="relu"),
    Dense(1, activation="sigmoid")
])

lstm_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

class_weight = {0:1, 1:2}

lstm_model.fit(
    X_tr_pad,
    y_tr,
    epochs=4,
    batch_size=1024,
    validation_split=0.1,
    class_weight=class_weight
)

import numpy as np

lstm_prob_tr = lstm_model.predict(X_tr_pad).flatten()
lstm_prob_te = lstm_model.predict(X_te_pad).flatten()

from sklearn.linear_model import LogisticRegression

# use small padded features
X_tr_lr = X_tr_pad[:, :20]
X_te_lr = X_te_pad[:, :20]

lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_tr_lr, y_tr)

lr_prob_tr = lr_model.predict_proba(X_tr_lr)[:,1]
lr_prob_te = lr_model.predict_proba(X_te_lr)[:,1]

from sklearn.ensemble import IsolationForest

iso = IsolationForest(n_estimators=100, contamination=0.03, random_state=42)

iso.fit(X_tr_lr)

if_tr = -iso.decision_function(X_tr_lr)
if_te = -iso.decision_function(X_te_lr)

# normalize
if_tr = (if_tr - if_tr.min()) / (if_tr.max() - if_tr.min())
if_te = (if_te - if_te.min()) / (if_te.max() - if_te.min())

final_prob = []

for i in range(len(lstm_prob_te)):

    #  Rule 1: strong anomaly
    if lstm_prob_te[i] > 0.7:
        final_prob.append(lstm_prob_te[i])

    #  Rule 2: medium confidence
    elif 0.4 < lstm_prob_te[i] <= 0.7:
        score = 0.6*lstm_prob_te[i] + 0.3*lr_prob_te[i] + 0.1*if_te[i]
        final_prob.append(score)

    #  Rule 3: low confidence
    else:
        score = 0.5*lr_prob_te[i] + 0.5*if_te[i]
        final_prob.append(score)

final_prob = np.array(final_prob)

# final prediction
y_pred = (final_prob > 0.4).astype(int)

from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import IsolationForest
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np

skf = StratifiedKFold(n_splits=4, shuffle=True, random_state=42)

acc_list, f1_list = [], []

tp_total, fp_total, fn_total, tn_total = 0, 0, 0, 0

for fold, (train_idx, val_idx) in enumerate(skf.split(X, y)):

    print(f"\n===== FOLD {fold+1} =====")

    X_train_fold = X.iloc[train_idx]
    y_train_fold = y[train_idx]

    X_val_fold = X.iloc[val_idx]
    y_val_fold = y[val_idx]

    # 🔹 Tokenization
    X_tr_str = X_train_fold.apply(lambda x: " ".join(x))
    X_val_str = X_val_fold.apply(lambda x: " ".join(x))

    tokenizer = Tokenizer()
    tokenizer.fit_on_texts(X_tr_str)

    X_tr_seq = tokenizer.texts_to_sequences(X_tr_str)
    X_val_seq = tokenizer.texts_to_sequences(X_val_str)

    # 🔹 Padding
    max_len = 50
    X_tr_pad = pad_sequences(X_tr_seq, maxlen=max_len, padding="post")
    X_val_pad = pad_sequences(X_val_seq, maxlen=max_len, padding="post")

    # 🔹 LSTM
    vocab_size = len(tokenizer.word_index) + 1

    lstm_model = Sequential([
        Embedding(vocab_size, 64),
        LSTM(64),
        Dropout(0.3),
        Dense(32, activation="relu"),
        Dense(1, activation="sigmoid")
    ])

    lstm_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

    class_weight = {0:1, 1:2}

    lstm_model.fit(
        X_tr_pad,
        y_train_fold,
        epochs=4,
        batch_size=1024,
        verbose=0,
        class_weight=class_weight
    )

    lstm_prob_tr = lstm_model.predict(X_tr_pad).flatten()
    lstm_prob_val = lstm_model.predict(X_val_pad).flatten()

    # 🔹 LR
    X_tr_lr = X_tr_pad[:, :20]
    X_val_lr = X_val_pad[:, :20]

    lr_model = LogisticRegression(max_iter=1000)
    lr_model.fit(X_tr_lr, y_train_fold)

    lr_prob_tr = lr_model.predict_proba(X_tr_lr)[:,1]
    lr_prob_val = lr_model.predict_proba(X_val_lr)[:,1]

    # 🔹 IF
    iso = IsolationForest(n_estimators=100, contamination=0.03, random_state=42)
    iso.fit(X_tr_lr)

    if_tr = -iso.decision_function(X_tr_lr)
    if_val = -iso.decision_function(X_val_lr)

    # normalize
    if_val = (if_val - if_val.min()) / (if_val.max() - if_val.min())

    #  SMART FUSION
    final_prob = []

    for i in range(len(lstm_prob_val)):

        if lstm_prob_val[i] > 0.7:
            final_prob.append(lstm_prob_val[i])

        elif 0.4 < lstm_prob_val[i] <= 0.7:
            score = 0.6*lstm_prob_val[i] + 0.3*lr_prob_val[i] + 0.1*if_val[i]
            final_prob.append(score)

        else:
            score = 0.5*lr_prob_val[i] + 0.5*if_val[i]
            final_prob.append(score)

    final_prob = np.array(final_prob)

    # prediction
    y_pred = (final_prob > 0.4).astype(int)

    # metrics
    acc = accuracy_score(y_val_fold, y_pred)
    f1 = f1_score(y_val_fold, y_pred)

    acc_list.append(acc)
    f1_list.append(f1)

    tn, fp, fn, tp = confusion_matrix(y_val_fold, y_pred).ravel()

    tn_total += tn
    fp_total += fp
    fn_total += fn
    tp_total += tp

    print("Accuracy:", acc)
    print("F1:", f1)
    print("TP:", tp, "FP:", fp, "FN:", fn, "TN:", tn)

#  FINAL RESULT
print("\n===== FINAL RESULT =====")
print("Avg Accuracy:", np.mean(acc_list))
print("Avg F1:", np.mean(f1_list))

print("\nTOTAL CONFUSION MATRIX:")
print("TP:", tp_total)
print("FP:", fp_total)
print("FN:", fn_total)
print("TN:", tn_total)